version: '3'

services:
  express:
    build: .
    container_name: express-app
    restart: always
    expose:
      - 3000

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express
